micromini-tool.completions: micromini-tool
	echo complete -W \"`./micromini-tool --shortlist`\" ./micromini-tool > $@
	echo complete -W \"`./micromini-tool --shortlist`\" micromini-tool>> $@

micromini-tool: micromini-tool.c


